
package com.oyun.media.transService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PortFuntionService", targetNamespace = "http://port.com/", wsdlLocation = "http://202.207.12.245:8080/ITMDTransService/PortFuntionPort?wsdl")
public class PortFuntionService
    extends Service
{

    private final static URL PORTFUNTIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException PORTFUNTIONSERVICE_EXCEPTION;
    private final static QName PORTFUNTIONSERVICE_QNAME = new QName("http://port.com/", "PortFuntionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://202.207.12.245:8080/ITMDTransService/PortFuntionPort?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PORTFUNTIONSERVICE_WSDL_LOCATION = url;
        PORTFUNTIONSERVICE_EXCEPTION = e;
    }

    public PortFuntionService() {
        super(__getWsdlLocation(), PORTFUNTIONSERVICE_QNAME);
    }

    public PortFuntionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PORTFUNTIONSERVICE_QNAME, features);
    }

    public PortFuntionService(URL wsdlLocation) {
        super(wsdlLocation, PORTFUNTIONSERVICE_QNAME);
    }

    public PortFuntionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PORTFUNTIONSERVICE_QNAME, features);
    }

    public PortFuntionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PortFuntionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PortFuntionDelegate
     */
    @WebEndpoint(name = "PortFuntionPort")
    public PortFuntionDelegate getPortFuntionPort() {
        return super.getPort(new QName("http://port.com/", "PortFuntionPort"), PortFuntionDelegate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PortFuntionDelegate
     */
    @WebEndpoint(name = "PortFuntionPort")
    public PortFuntionDelegate getPortFuntionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://port.com/", "PortFuntionPort"), PortFuntionDelegate.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PORTFUNTIONSERVICE_EXCEPTION!= null) {
            throw PORTFUNTIONSERVICE_EXCEPTION;
        }
        return PORTFUNTIONSERVICE_WSDL_LOCATION;
    }

}
