
package com.oyun.media.transService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PortFuntionDelegate", targetNamespace = "http://port.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PortFuntionDelegate {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fileITMDTrans", targetNamespace = "http://port.com/", className = "com.port.FileITMDTrans")
    @ResponseWrapper(localName = "fileITMDTransResponse", targetNamespace = "http://port.com/", className = "com.port.FileITMDTransResponse")
    public String fileITMDTrans(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fileITMDTransWithSpace", targetNamespace = "http://port.com/", className = "com.port.FileITMDTransWithSpace")
    @ResponseWrapper(localName = "fileITMDTransWithSpaceResponse", targetNamespace = "http://port.com/", className = "com.port.FileITMDTransWithSpaceResponse")
    public String fileITMDTransWithSpace(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0)
        throws Exception_Exception
    ;

}
