
package com.oyun.media.port;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PortFunctionService", targetNamespace = "http://port.com/", wsdlLocation = "http://202.207.12.245:8080/newChecker/PortFunctionPort?wsdl")
public class PortFunctionService
    extends Service
{

    private final static URL PORTFUNCTIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException PORTFUNCTIONSERVICE_EXCEPTION;
    private final static QName PORTFUNCTIONSERVICE_QNAME = new QName("http://port.com/", "PortFunctionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://202.207.12.245:8080/newChecker/PortFunctionPort?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PORTFUNCTIONSERVICE_WSDL_LOCATION = url;
        PORTFUNCTIONSERVICE_EXCEPTION = e;
    }

    public PortFunctionService() {
        super(__getWsdlLocation(), PORTFUNCTIONSERVICE_QNAME);
    }

    public PortFunctionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PORTFUNCTIONSERVICE_QNAME, features);
    }

    public PortFunctionService(URL wsdlLocation) {
        super(wsdlLocation, PORTFUNCTIONSERVICE_QNAME);
    }

    public PortFunctionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PORTFUNCTIONSERVICE_QNAME, features);
    }

    public PortFunctionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PortFunctionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PortFunctionDelegate
     */
    @WebEndpoint(name = "PortFunctionPort")
    public PortFunctionDelegate getPortFunctionPort() {
        return super.getPort(new QName("http://port.com/", "PortFunctionPort"), PortFunctionDelegate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PortFunctionDelegate
     */
    @WebEndpoint(name = "PortFunctionPort")
    public PortFunctionDelegate getPortFunctionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://port.com/", "PortFunctionPort"), PortFunctionDelegate.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PORTFUNCTIONSERVICE_EXCEPTION!= null) {
            throw PORTFUNCTIONSERVICE_EXCEPTION;
        }
        return PORTFUNCTIONSERVICE_WSDL_LOCATION;
    }

}
