
package com.oyun.media.port;

import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PortFunctionDelegate", targetNamespace = "http://port.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PortFunctionDelegate {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "function", targetNamespace = "http://port.com/", className = "com.port.Function")
    @ResponseWrapper(localName = "functionResponse", targetNamespace = "http://port.com/", className = "com.port.FunctionResponse")
    public String function(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0)
        throws Exception_Exception
    ;

}
